providers = ['rust', 'node','...']

[phases.setup]
nixOverlays = [
    'https://github.com/dreadsfun/rust-overlay/archive/master.tar.gz',
]

[phases.install]
cmds = ["...","./install.sh"]

[phases.build]
cmds = ["...","./build.sh"]

[start]
cmd = "./start.sh"